# Generated by Django 3.2.25 on 2024-12-30 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='weather',
            name='country_code',
            field=models.CharField(default='us', max_length=2),
        ),
    ]
